### Criar um novo pedido (REST)
POST http://localhost:8080/orders
Content-Type: application/json

{
  "id": "550e8400-e29b-41d4-a716-446655440010",
  "price": 200.0,
  "tax": 20.0
}

###

### Listar todos os pedidos (REST)
GET http://localhost:8080/orders

###

### Listar pedidos (GraphQL)
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "query { listOrders { id product price createdAt } }"
}

###

### Criar pedido (GraphQL)
POST http://localhost:8080/graphql
Content-Type: application/json

{
  "query": "mutation { createOrder(input: {id: \"550e8400-e29b-41d4-a716-446655440011\", price: 150, tax: 15}) { id price tax finalPrice } }"
}
